//src/lib/reports/reportTranslations.ts
type ReportTranslationDictionary = Record<string, string>;

const REPORT_TRANSLATIONS: Record<string, ReportTranslationDictionary> = {
  en: {
    monthlyReport: "Monthly Report",
    businessReport: "Business report",
    totalMessages: "Total messages",
    totalMessagesSubtitle: "Customer and assistant messages",
    uniqueCustomers: "Unique customers",
    uniqueCustomersSubtitle: "Unique contacts detected",
    voiceCalls: "Voice calls",
    estimatedFromHistory: "Estimated from history",
    basedOnRealCalls: "Based on real call records",
    estimatedTimeSaved: "Estimated time saved",
    estimatedHours: "{{hours}} hours estimated",
    timeSavedSubtitle: "Based on messages, calls, and bookings",

    bookings: "Bookings",
    bookingsSubtitle:
      "Booking activity created by Aamy during this period.",
    conversion: "{{rate}}% conversion",
    started: "Started",
    created: "Created",
    confirmed: "Confirmed",

    conversationsByChannel: "Conversations by channel",
    capturedLeads: "Captured leads",
    capturedLeadsSubtitle:
      "New contacts identified by Aamy during this period.",
    leadsGenerated: "leads generated this month",
    afterHoursCalls: "After-hours calls: {{calls}}",
    afterHoursUnavailable: "After-hours calls: not available",

    intelligentAnalysis: "Intelligent Business Analysis",
    executiveSummary: "Executive Summary",
    keyInsights: "Key Insights",
    recommendations: "Recommendations",
    insufficientData:
      "Not enough data was available for this section.",
    generatedAtUnavailable: "Not available",

    reportFooter:
      "Generated by Aamy AI. Metrics may vary depending on integrations, configuration, and available records.",
    analysisFooter:
      "Analysis generated by Aamy AI · {{date}}. Recommendations are based only on available report data.",
  },

  es: {
    monthlyReport: "Reporte mensual",
    businessReport: "Reporte del negocio",
    totalMessages: "Mensajes totales",
    totalMessagesSubtitle: "Mensajes de clientes y del asistente",
    uniqueCustomers: "Clientes únicos",
    uniqueCustomersSubtitle: "Contactos únicos detectados",
    voiceCalls: "Llamadas de voz",
    estimatedFromHistory: "Estimado a partir del historial",
    basedOnRealCalls: "Basado en registros reales de llamadas",
    estimatedTimeSaved: "Tiempo estimado ahorrado",
    estimatedHours: "{{hours}} horas estimadas",
    timeSavedSubtitle: "Basado en mensajes, llamadas y reservas",

    bookings: "Reservas",
    bookingsSubtitle:
      "Actividad de reservas creada por Aamy durante este período.",
    conversion: "{{rate}}% de conversión",
    started: "Iniciadas",
    created: "Creadas",
    confirmed: "Confirmadas",

    conversationsByChannel: "Conversaciones por canal",
    capturedLeads: "Contactos capturados",
    capturedLeadsSubtitle:
      "Nuevos contactos identificados por Aamy durante este período.",
    leadsGenerated: "contactos generados este mes",
    afterHoursCalls: "Llamadas fuera de horario: {{calls}}",
    afterHoursUnavailable: "Llamadas fuera de horario: no disponible",

    intelligentAnalysis: "Análisis inteligente del negocio",
    executiveSummary: "Resumen ejecutivo",
    keyInsights: "Hallazgos principales",
    recommendations: "Recomendaciones",
    insufficientData:
      "No hubo suficientes datos disponibles para esta sección.",
    generatedAtUnavailable: "No disponible",

    reportFooter:
      "Generado por Aamy AI. Las métricas pueden variar según las integraciones, la configuración y los registros disponibles.",
    analysisFooter:
      "Análisis generado por Aamy AI · {{date}}. Las recomendaciones se basan únicamente en los datos disponibles del reporte.",
  },

  pt: {
    monthlyReport: "Relatório mensal",
    businessReport: "Relatório da empresa",
    totalMessages: "Total de mensagens",
    totalMessagesSubtitle: "Mensagens de clientes e do assistente",
    uniqueCustomers: "Clientes únicos",
    uniqueCustomersSubtitle: "Contatos únicos detectados",
    voiceCalls: "Chamadas de voz",
    estimatedFromHistory: "Estimado a partir do histórico",
    basedOnRealCalls: "Baseado em registros reais de chamadas",
    estimatedTimeSaved: "Tempo estimado economizado",
    estimatedHours: "{{hours}} horas estimadas",
    timeSavedSubtitle: "Baseado em mensagens, chamadas e reservas",

    bookings: "Reservas",
    bookingsSubtitle:
      "Atividade de reservas criada pela Aamy durante este período.",
    conversion: "{{rate}}% de conversão",
    started: "Iniciadas",
    created: "Criadas",
    confirmed: "Confirmadas",

    conversationsByChannel: "Conversas por canal",
    capturedLeads: "Contatos capturados",
    capturedLeadsSubtitle:
      "Novos contatos identificados pela Aamy durante este período.",
    leadsGenerated: "contatos gerados neste mês",
    afterHoursCalls: "Chamadas fora do horário: {{calls}}",
    afterHoursUnavailable: "Chamadas fora do horário: indisponível",

    intelligentAnalysis: "Análise inteligente do negócio",
    executiveSummary: "Resumo executivo",
    keyInsights: "Principais insights",
    recommendations: "Recomendações",
    insufficientData:
      "Não havia dados suficientes disponíveis para esta seção.",
    generatedAtUnavailable: "Indisponível",

    reportFooter:
      "Gerado pela Aamy AI. As métricas podem variar dependendo das integrações, configurações e registros disponíveis.",
    analysisFooter:
      "Análise gerada pela Aamy AI · {{date}}. As recomendações são baseadas apenas nos dados disponíveis do relatório.",
  },
};

function normalizeReportLanguage(value: unknown): string {
  const raw = String(value ?? "")
    .trim()
    .toLowerCase()
    .replace(/_/g, "-");

  if (!raw) {
    return "en";
  }

  return raw.split("-")[0] || "en";
}

function interpolate(
  template: string,
  variables?: Record<string, string | number>
): string {
  if (!variables) {
    return template;
  }

  let result = template;

  for (const [key, value] of Object.entries(variables)) {
    result = result
      .split(`{{${key}}}`)
      .join(String(value));
  }

  return result;
}

export function createReportTranslator(language: unknown) {
  const normalizedLanguage =
    normalizeReportLanguage(language);

  const dictionary =
    REPORT_TRANSLATIONS[normalizedLanguage] ??
    REPORT_TRANSLATIONS.en;

  return (
    key: string,
    variables?: Record<string, string | number>
  ): string => {
    const template =
      dictionary[key] ??
      REPORT_TRANSLATIONS.en[key] ??
      key;

    return interpolate(template, variables);
  };
}