name: Docker Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔐 Login a Docker Hub (usa los secrets que vas a crear en Settings → Secrets → Actions)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false   # cámbialo a true si quieres subir la imagen a Docker Hub
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatbot-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
